version: 0.0.1
pipeline_name: graphpred
device: cpu                   # Torch device name, e.q. cpu or cuda or cuda:0
data:
  name: ogbg-molhiv
  split_ratio:                # Ratio to generate data split, for example set to [0.8, 0.1, 0.1] for 80% train/10% val/10% test. Leave blank to use builtin split in original dataset
general_pipeline:
  num_runs: 10                # Number of experiments to run
  train_batch_size: 128       # Graph batch size when training
  eval_batch_size: 128        # Graph batch size when evaluating
  optimizer:
    name: Adam
    lr: 0.01
    weight_decay: 3e-6
  num_epochs: 200             # Number of training epochs
