apiVersion: v1
kind: Pod
spec:
  securityContext:
    runAsUser: 0
  containers:
    - name: dgl-ci-cpp
      image: dgllib/dgl-ci-gpu:conda
      imagePullPolicy: Always
      tty: true
      resources:
        limits:
          nvidia.com/gpu: 1 # requesting 1 GPU
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: beta.kubernetes.io/instance-type
            operator: In
            values:
            - p3.2xlarge