apiVersion: v1
kind: Pod
spec:
  securityContext:
    runAsUser: 0
  serviceAccountName: dglciuser
  containers:
  - name: dgl-ci-gpu-compile
    image: dgllib/dgl-ci-gpu:conda
    imagePullPolicy: Always
    tty: true
    command:
      - "bash"
    args:
      - "-c"
      - |
        curl "https://data.dgl.ai/assets/sccache" -o "/usr/local/bin/sccache"
        chmod +x /usr/local/bin/sccache
        sccache -s
    env:
      - name: CMAKE_CACHE_EXTRA_ARGS
        value: " -DCMAKE_C_COMPILER_LAUNCHER=sccache -DCMAKE_CXX_COMPILER_LAUNCHER=sccache "
      - name: SCCACHE_BUCKET
        value: "dgl-build-cache"
      - name: SCCACHE_REGION
        value: "us-west-2"
    resources:
      requests:
        cpu: 32
  # affinity:
  #   nodeAffinity:
  #     requiredDuringSchedulingIgnoredDuringExecution:
  #       nodeSelectorTerms:
  #       - matchExpressions:
  #         - key: beta.kubernetes.io/instance-type
  #           operator: In
  #           values:
  #           - c5.9xlarge