name: mxnet-ci
dependencies:
  - python=3.7.9
  - pip
  - pip:
    - mxnet-cu110==1.8.0.post0
    - pytest
    - nose
    - numpy
    - cython
    - scipy
    - networkx
    - matplotlib
    - nltk
    - requests[security]
    - tqdm
