
name: tensorflow-ci
dependencies:
  - pip
  - pip:
    - tensorflow-gpu==2.1.0rc1
    - tfdlpack-gpu
    - pytest
  - nose
  - numpy
  - cython
  - scipy
  - networkx
  - matplotlib
  - nltk
  - requests[security]
  - tqdm
