name: tensorflow-ci
dependencies:
  - pip
  - pip:
    - tensorflow==2.1.0rc1
    - tfdlpack
    - pytest
  - nose
  - numpy
  - cython
  - scipy
  - networkx
  - matplotlib
  - nltk
  - requests[security]
  - tqdm
