name: pytorch-ci
channels:
  - pytorch
dependencies:
  - python = 3.6
  - pip
  - pip:
    - torch
    - torchvision
    - pytest
  - torchvision
  - nose
  - numpy
  - cython
  - scipy
  - networkx
  - matplotlib
  - nltk
  - requests[security]
  - tqdm