package:
  name: dgl
  version: "0.0.1"

source:
  git_rev: "0.0.1"
  git_url: https://github.com/jermainewang/dgl.git

requirements:
  build:
    - python >=3.5
    - setuptools
    - cmake
    - m2w64-gcc # [win]
  run:
    - python
    - numpy
    - scipy
    - networkx

about:
  home: https://github.com/jermainewang/dgl.git
  license: Apache
  license_file: ../LICENSE
